import { Inter } from "next/font/google";
import "./globals.css";


export const metadata = {
  title: "Mood-Mate",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <body>{children}</body>
    </html>
  );
}
